<?php

namespace App\Http\Controllers;

use App\Models\Reminder;
use App\Models\Tender;
use Illuminate\Http\JsonResponse;

class NotificationController extends Controller
{
    /**
     * Return bell notifications for the authenticated user.
     *
     * Sources (merged, deduplicated):
     *  1. Pending reminders from the reminders table (generated by scheduler)
     *  2. Real-time: overdue tenders with deadline passed
     *  3. Real-time: tenders with deadline within 14 days
     *
     * Scoped to tenders where user is PIC/creator, unless Manager/Admin.
     */
    public function index(): JsonResponse
    {
        $user      = auth()->user();
        $showAll   = $user->hasRole('Super Admin') || $user->hasRole('Marketing Manager');
        $finalStatuses = ['completed', 'cancelled'];

        // ── 1. Pending reminders from scheduler ─────────────────────────────
        $reminders = Reminder::where('user_id', $user->id)
            ->where('status', 'pending')
            ->with(['tender', 'proposal'])
            ->orderByDesc('created_at')
            ->limit(10)
            ->get()
            ->map(fn($r) => [
                'type'     => str_starts_with($r->title, '[Overdue') || str_contains($r->title, 'Overdue') ? 'overdue' : 'upcoming',
                'id'       => $r->tender_id ?? $r->proposal_id,
                'title'    => $r->tender?->title ?? $r->proposal?->title ?? $r->title,
                'code'     => $r->tender?->code ?? $r->proposal?->code ?? '',
                'deadline' => $r->tender?->submission_deadline?->format('d M Y')
                           ?? $r->proposal?->deadline?->format('d M Y')
                           ?? '—',
                'days'     => $r->description,
                'url'      => $r->tender_id
                    ? route('tenders.show', $r->tender_id)
                    : ($r->proposal_id ? route('proposals.show', $r->proposal_id) : '#'),
                'source'   => 'reminder',
                'reminder_id' => $r->id,
            ]);

        // ── 2+3. Real-time deadline alerts (always fresh) ───────────────────
        $base = Tender::with(['client', 'pic'])
            ->whereNotIn('status', $finalStatuses)
            ->whereNotNull('submission_deadline')
            ->unless($showAll, fn($q) => $q->where(fn($q2) =>
                $q2->where('pic_id', $user->id)
                   ->orWhere('created_by', $user->id)
            ));

        $overdue = (clone $base)
            ->where('submission_deadline', '<', now())
            ->orderBy('submission_deadline')
            ->limit(5)
            ->get()
            ->map(fn($t) => [
                'type'     => 'overdue',
                'id'       => $t->id,
                'title'    => $t->title,
                'code'     => $t->code,
                'deadline' => $t->submission_deadline->format('d M Y'),
                'days'     => abs($t->days_until_deadline) . ' hari lalu',
                'url'      => route('tenders.show', $t),
                'source'   => 'realtime',
            ]);

        $upcoming = (clone $base)
            ->where('submission_deadline', '>=', now())
            ->where('submission_deadline', '<=', now()->addDays(14))
            ->orderBy('submission_deadline')
            ->limit(5)
            ->get()
            ->map(fn($t) => [
                'type'     => 'upcoming',
                'id'       => $t->id,
                'title'    => $t->title,
                'code'     => $t->code,
                'deadline' => $t->submission_deadline->format('d M Y'),
                'days'     => $t->days_until_deadline === 0 ? 'Hari ini' : 'H-' . $t->days_until_deadline,
                'url'      => route('tenders.show', $t),
                'source'   => 'realtime',
            ]);

        // ── Merge: reminders first, then real-time (deduplicate by url) ─────
        $seen = [];
        $merged = collect();

        foreach ($reminders->concat($overdue)->concat($upcoming) as $item) {
            $key = $item['url'];
            if (!isset($seen[$key])) {
                $seen[$key] = true;
                $merged->push($item);
            }
        }

        $final = $merged->take(15)->values();

        return response()->json([
            'count'         => $final->count(),
            'notifications' => $final,
        ]);
    }

    /**
     * Mark a reminder as read/completed.
     */
    public function markRead(int $reminderId): JsonResponse
    {
        $reminder = Reminder::where('id', $reminderId)
            ->where('user_id', auth()->id())
            ->firstOrFail();

        $reminder->update(['status' => 'completed']);

        return response()->json(['success' => true]);
    }
}
